#upstream api { 
#    server api:3000;
#}

upstream exchange_api {
    server api1:3000 max_fails=3 fail_timeout=10s;
    server api2:3000 max_fails=3 fail_timeout=10s;
    server api3:3000 max_fails=3 fail_timeout=10s;
}

server {
    listen 80;

    location / {
        proxy_pass http://exchange_api;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Si una instancia cae, reintenta en otra.
        proxy_next_upstream error timeout;

        # Este header está para ver en Postman el balanceo de carga.
        add_header X-Served-By $upstream_addr always;
    }
}