limit_req_zone $binary_remote_addr zone=api_rate_limit:10m rate=300r/s;
limit_req_status 429;
limit_req_log_level warn;

upstream api { 
    server exchange-api-1:3000;
}

server {
    listen 80;

    location / {
        limit_req zone=api_rate_limit burst=50 nodelay;

        proxy_pass http://api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}